# Generated by Django 5.1.1 on 2024-09-13 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(choices=[('office_user', 'Office User'), ('website', 'Website Form'), ('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp')], default='website', help_text='Describes how the lead was created or the source of creation.', max_length=50)),
                ('inquiry_type', models.CharField(choices=[('work_visa', 'Work Visa'), ('student_visa', 'Student Visa'), ('visitor_visa', 'Visitor Visa'), ('family_visa', 'Family Visa'), ('residency_visa', 'Residency Visa'), ('investment_visa', 'Investment or Business Visa'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('dismissed', 'Dismissed'), ('converted', 'Converted to Contact')], default='new', max_length=20)),
                ('subscribe_to_mailing_list', models.BooleanField(default=False, help_text='Indicates if the lead wants to subscribe to the mailing list for marketing emails.')),
                ('notes', models.TextField(blank=True, help_text='Additional information or context about the lead (e.g., details from a phone call, email, or form submission).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Agent responsible for managing the lead. Can be null if unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the lead. Could be an internal user or left blank if created externally.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
