# Generated by Django 5.1.1 on 2024-09-17 03:55

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_lead_created_by_id_remove_lead_updated_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.CharField(default='website', help_text='Indicates the source of creation. Default is "website".', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
