# Generated by Django 5.1.1 on 2024-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_created_by_alter_lead_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_id',
            field=models.IntegerField(default=0, help_text='ID of the user who created the lead. Default is 0 for website.'),
        ),
    ]
